PAGE_SIZE = 20

SCREENER = {
    "america": "United States", 
    "forex": "Forex", 
    "crypto": "Cryptocurrency", 
    "indonesia": "Indonesia", 
    "india" : "India", 
    "italy": "Italy",
    "cfd": "CFD", 
    "uk": "United Kingdom", 
    "brazil": "Brazil", 
    "vietnam": "Vietnam", 
    "rsa": "South Africa", 
    "ksa": "Saudi Arabia",
    "australia": "Australia", 
    "russia": "Russia", 
    "thailand": "Thailand", 
    "philippines": "Philippines", 
    "taiwan": "Taiwan", 
    "sweden": "Sweden", 
    "france": "France", 
    "turkey": "Turkey", 
    "euronext": "Euronext", 
    "germany": "Germany", 
    "spain": "Spain", 
    "hongkong": "Hong Kong", 
    "korea": "South Korea",
    "malaysia": "Malaysia",
    "canada": "Canada",
}
